tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-tertiary-container": "#ffede6",
                "surface-container-high": "#25293a",
                "surface-variant": "#2f3445",
                "surface-dim": "#0e1322",
                "on-primary-fixed-variant": "#003ea8",
                "outline-variant": "#434655",
                "error-container": "#93000a",
                "surface-container-low": "#161b2b",
                "surface-container": "#1a1f2f",
                "surface-tint": "#b4c5ff",
                "primary-fixed": "#dbe1ff",
                "surface-container-lowest": "#090e1c",
                "on-secondary": "#00354a",
                "on-background": "#dee1f7",
                "on-tertiary-fixed-variant": "#7d2d00",
                "on-secondary-fixed-variant": "#004c69",
                "secondary-container": "#00a6e0",
                "on-surface-variant": "#c3c6d7",
                "on-surface": "#dee1f7",
                "inverse-on-surface": "#2b3040",
                "background": "#0e1322",
                "on-primary-container": "#eeefff",
                "surface-container-highest": "#2f3445",
                "inverse-surface": "#dee1f7",
                "secondary-fixed": "#c4e7ff",
                "secondary": "#7bd0ff",
                "tertiary": "#ffb596",
                "on-secondary-fixed": "#001e2c",
                "tertiary-fixed": "#ffdbcd",
                "surface-bright": "#343949",
                "on-error-container": "#ffdad6",
                "primary-fixed-dim": "#b4c5ff",
                "secondary-fixed-dim": "#7bd0ff",
                "inverse-primary": "#0053db",
                "primary-container": "#2563eb",
                "on-primary": "#002a78",
                "tertiary-fixed-dim": "#ffb596",
                "on-secondary-container": "#00374d",
                "tertiary-container": "#bc4800",
                "error": "#ffb4ab",
                "on-tertiary": "#581e00",
                "outline": "#8d90a0",
                "on-error": "#690005",
                "on-primary-fixed": "#00174b",
                "on-tertiary-fixed": "#360f00",
                "primary": "#b4c5ff",
                "surface": "#0e1322"
            },
            fontFamily: {
                "headline": ["Space Grotesk"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
        },
    },
}
